semi-colons now enforced
updated parser, and manual.

Brett, there are now two exceptions which would benefit from clearer messages from us, and from removing all the extra python error stuff that gets printed.

1. If we're missing a semi-colon in the [partitions] section, we get this:
partfinder.pyparsing.ParseException: Expected "[schemes]" (at char 1072), (line:43, col:1)

2. If we're missing a semi-colon most other places, we get this:
partfinder.pyparsing.ParseException: Expected ";" (at char 554), (line:16, col:1)

Do you think we can catch them?

R